# Converted from notebook: 2.ipynb

# --- Cell 1 (markdown) ---
# # Problem - 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# $$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...$$
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#

# --- Cell 2 (code) ---
def fibonacci_series(max_num):
    i1, i2 = 0, 1
    fibonacci_series = [0]
    while i2 < max_num:
        fibonacci_series.append(i2)
        i2, i1 = i1 + i2, i2
    
    return fibonacci_series

# --- Cell 3 (code) ---
fibs = fibonacci_series(4000000)
even_fib = sum([fib for fib in fibs if fib%2 == 0])
even_fib
